[design] 회원가입 UI제작
BCSDLab/KOIN_OWNER_iOS pull request #8
Opened 2024-07-05 13:10 UTC by KimNahun

## #️⃣연관된 이슈

- #5 

## 📝작업 내용

회원가입 3개의 화면의 UI 구현을 완료했습니다

### 스크린샷 (선택)

<p align="center">
<img width="150" alt="Capture" src="https://github.com/BCSDLab/KOIN_OWNER_iOS/assets/118811606/1dc6aac7-670e-4374-8f9e-d2ef62d4de19">
<img width="150" alt="Capture 1" src="https://github.com/BCSDLab/KOIN_OWNER_iOS/assets/118811606/fe11a675-c4dc-4eca-830b-087514f5343d">
<img width="150" alt="Capture 2" src="https://github.com/BCSDLab/KOIN_OWNER_iOS/assets/118811606/6b4f9852-53fc-4579-aa9a-13623de74f38">
</p>

## 💬리뷰 요구사항(선택)

View에서 이름값이 변하면 상위 뷰에서도 이런 String을 @State로 가지고
하위 뷰에서는 그걸 @Binding으로 가지는데 더 나은 방법이 있는지 궁금합니다. 

```
struct BusinessVerificationView: View {
    @State private var ownerName: String = ""
    @State private var shopName: String = ""
    @State private var businessRegistrationNumber: String = ""
```

```
struct CustomTextField: View {
    let placeholder: String
    var isSecure: Bool
    @Binding var text: String

```

그리고 SwiftUI에서는 버튼의 enable 토글을 View안에서 @State 로 가져야할까요? View 내에 Model을 가지고 있다는 느낌이 
들었던 것 같아요.
나중에 TCA로 바꾸면서 분리시켜야 하는거겠죠?

```
    @State private var isAgreeAllButtonToggled = false
    @State private var isPersonalInformationButtonToggled = false
    @State private var isKoinButtonToggled = false
```

2024-07-05 22:16 UTC, JeongYeongJoon requested changes
약간의 수정이 필요한 부분이 보여 Request 드립니다.
리뷰로 쓴 내용 뿐만 아니라 전체적으로 Button이나 Stack을 사용할 때 코드 스타일이 조금 달라서 이 부분도 논의가 필요할 듯 합니다.

아 그리고 가능하시다면 Rebase도 부탁드립니다.
수고많으십니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +    @State private var isKoinButtonToggled = false
데이터로 인한 View의 상태 변화가 아닌 단순히 View의 상태 변화를 ViewModel이나 ViewStore에서 관리하는건 너무 역할이 방대해진다고 보기 때문에 데이터에 영향을 받지 않는 상태일 경우 View에 두는 편입니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                }.frame(maxWidth: .infinity, minHeight: 40).background(Color.neutral100).padding(.top, 9)
viewModifier들을 어떤건 한 줄로 쓰고 어떤건 개행하는 이유가 있을까요?

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                }.padding(.top, 16).padding(.bottom, 16)
위 아래 padding이 같을 경우
`.padding(.vertical, 16)`
으로 간소화 시킬 수 있습니다.
마찬가지로 `.horizontal` 도 가능합니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                        .cornerRadius(4)
`.cornerRadius` 는 deprecated 될 예정이라 `.clipShape(RoundedRectangle(cornerRadius: 4))` 로 쓰시는걸 추천드립니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/RegistrationFormView.swift
> +        NavigationView {
상위 View가 이미 NavigationView이기 때문에 하위 View들은 NavigationView가 필요하지 않습니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
3개의 View를 Navigation으로 처리하신 이유가 궁금합니다. ProgressBar가 포함되어있고, NavigationBar 또한 변하지 않는다면 최상위에 RegisterView를 두고 NavigationBar와 ProgressBar를 고정시킨 뒤에 세부 View를 갈아끼우는 방식도 고려해보시면 좋을 것 같습니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Common/Components/CustomTextField.swift
> +    @Binding var text: String
여기서 사용하신 TextField와 같이 하위 View에서의 상태 변화를 상위 View에서 관찰해야하는 경우에는 어쩔 수 없이 `@Binding` 을 사용해야 합니다.
다만 `@Binding`을 사용할 경우 우려하셨을 것처럼 데이터 흐름 추적이 어려워지고 코드가 복잡해지는 경향이 있어 꼭 필요한 경우가 아니라면 저도 사용을 지양하는 편입니다.

2024-07-05 22:16 UTC, JeongYeongJoon commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
단순히 화면의 가로 길이를 가져오기 위한 것이라면 GeometryReader는 불필요할 것 같습니다.

2024-07-06 03:47 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                }.frame(maxWidth: .infinity, minHeight: 40).background(Color.neutral100).padding(.top, 9)
되도록 한줄로 표현가능한건 줄바꿈이 많아지면 코드가 길어져서 가독성을 위해서 였습니다~
이 부분도 통일이 필요해보이네요

2024-07-06 11:06 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +    @State private var isKoinButtonToggled = false
UIKit에서는 button의 isSelected 를 통해 바인딩할수있는데 비슷한 방법이 있는지 궁금했습니다!

2024-07-06 11:06 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                }.padding(.top, 16).padding(.bottom, 16)
수정하겠습니당

2024-07-06 11:08 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/RegistrationFormView.swift
> +        NavigationView {
첫번째 페이지를 말씀하시는건가요? 
우선 나중에 NavigationView들을 다 지울 예정인데 우선 화면에 어떤식으로 보여지는지 각각 확인하기 위해 
각각의 페이지를 연결하기 전에 페이지마다
NavigationView를 추가하였습니다.

2024-07-06 11:10 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
좋은 방식인 것 같습니다!

다음 버튼이 탭될때 progressbar의 진행도와 Text를 변화시킬 수 있을 것 같네요.
그렇다면 하위 각각의 3개의 View에서 상위 RegiserView로 이벤트를 전송해야하는데 이것도 Binding과 State로 이루어 져야 할까요 ?

2024-07-06 13:38 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
위와 같은 형태로 구현하게 될 경우 상위 View에서 데이터를 관리하고 하위 View들은 따로 선언하는 것이 아닌 상위 View의 Extension 형태로 구현한다면 데이터 관리가 쉽게 가능할 것 같습니다.

2024-07-06 23:39 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +    @State private var isKoinButtonToggled = false
아쉽게도 SwiftUI에서는 해당 기능이 없어 Button을 커스텀해서 사용해야합니다.

2024-07-07 10:29 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
그렇다면 현재 View가 3개인데 이걸 1개의 View로 만들고, 나머지 3개를 각각 extension으로 하라는 말씀이신가요?

제 생각에는 extension한 코드에는 stored property를 선언할수 없어서 결국 최상단 루트 View에서 하위 Extension하는 properties 들 ( isToggled, password ) 을 모두 가지고 있어야 해서 오히려 불편할수도 있지않을까 라고도 생각합니다.

2024-07-07 10:31 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
```
@State private var isAgreeAllButtonToggled = false
    @State private var isPersonalInformationButtonToggled = false
    @State private var isKoinButtonToggled = false
     @State private var phoneNumber: String = ""
     @State private var verificationCode: String = ""
     @State private var password: String = ""
     @State private var confirmPassword: String = ""
      @State private var ownerName: String = ""
    @State private var shopName: String = ""
    @State private var businessRegistrationNumber: String = ""
```

를 모두 하나의 파일에 가지고 있는다면 데이터 상태 추적 등등에서도 안좋지 않을까요 ?

2024-07-07 10:35 UTC, KimNahun commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
관련해서 찾아봤는데 GeometryReader가 부모의 width를 가져와서 여기서 UIScreen.main.width를 사용하면 대응이 안되기 때문에 GeometryReader를 다시 사용하였습니다. 더 좋은 방법이 있을까요 ?

2024-07-07 23:28 UTC, JeongYeongJoon commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
대응이 안된다는게 다른 상황에서 해당 컴포넌트를 사용할 때 width를 가변적으로 사용할 수 없다는 뜻인가요?

2024-07-07 23:43 UTC, JeongYeongJoon commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
그럴 수 있을 것 같네요. TCA 적용 시 데이터 관리를 어떻게해야할지 감이 잘 안잡혀서 좀 찾아봤는데
https://medium.com/@sylpid003/swiftui-%ED%83%AD-%EB%A9%94%EB%89%B4-%EB%A7%8C%EB%93%A4%EA%B8%B0-2-tca-%EC%A0%81%EC%9A%A9-d488a26a5c69
좋은 예시가 있어서 가져왔습니다.
처음 제시하신 방법처럼 Extension이 아니라 개별적인 View 4개를 만들어 @Binding 으로 값을 받는 방식으로 사용하면 될 것 같습니다.

2024-07-08 07:03 UTC, KimNahun commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
가변적으로 width를 사용하지 않고 부모의 view의 width를 가져오는 것입니다.
위에 
```
RoundedRectangle(cornerRadius: 4)
                    .frame(height: 3)
                    .foregroundStyle(Color.neutral200)
```
에서는 따로 width를 선언해주지 않았는데 여기서 위의 width가 자동으로 계산되는 이유는 GeometryReader 의 너비를 사용하기 때문입니다. 
따라서 아래에 width를 계산해주기 위해선 GeometryReader 가 필요하다고 생각했습니다.

가변적으로 입력값을 width로 주는게 아닌 선언하면서 같이 width를 알아서 계산해주는게 장점이라고 생각했습니다.

2024-07-08 07:06 UTC, KimNahun commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
커스텀뷰에서 width를 선언안하면 GeometryReader 는 사용되어서 부모 뷰의 높이가 할당되지만 생략된 형태로 주어진다고 이해했습니다

2024-07-08 07:09 UTC, KimNahun commented on koinOwner/Sources/Modules/Register/PolicyAgreementView.swift
> +                    .frame(height: 8).padding(.top, 8)
rootview가 있고 진행상황에 따라 3개의 childview를 switch하는 방식으로 수정했습니다.
코드적으로는 깔끔해진 느낌이 듭니다. 하지만 단점도 조금 있다고 느끼는게 전에는 각각이 다른 view여서 서로에 영향을 미치지 않았지만
이제 그걸 공통적으로 관리하는 rootview가 있어서 각각의 하위 view마다 진행상황이 완료된 것을 rootview에게 알려주어야 하고
바인딩이 되어야 한다고 느꼈습니다.

2024-07-08 07:25 UTC, JeongYeongJoon commented on koinOwner/Sources/Common/Components/CustomProgressBar.swift
> +        }
ProgressView를 한군데에서 사용한다고 가정하고 생각해서 UIScreen.main.bounds.size.width를 말씀 드린건데 컴포넌트처럼 사용하려면 나훈님 방식이 더 맞는 것 같습니다.

2024-07-08 07:26 UTC, JeongYeongJoon approved these changes

2024-07-08 08:02 UTC, merged